Repository neondatabase/neon, pull requests merged in 2023-07, with the labels that each got.

#4632 Update `pgvector` to 0.4.4
  Dockerfile.compute-node
Labels: /release-notes

#4482 cold starts: basebackup compression
  Cargo.lock
  Cargo.toml
  compute_tools/Cargo.toml
  compute_tools/src/compute.rs
  libs/compute_api/src/responses.rs
  libs/utils/src/measured_stream.rs
  pageserver/Cargo.toml
  pageserver/src/page_service.rs
  test_runner/performance/test_startup.py
Labels: a/performance, a/benchmark

#4723 Document recommended ccls setup
  docs/tools.md
Labels: a/internal_devx

#4683 test_runner: run benchmarks in parallel
  .github/actions/run-python-test-set/action.yml
  .github/workflows/build_and_test.yml
  poetry.lock
  pyproject.toml
  scripts/benchmark_durations.py
Labels: run-benchmarks

#4734 python: more linting
  pyproject.toml
  scripts/export_import_between_pageservers.py
  test_runner/fixtures/benchmark_fixture.py
  test_runner/fixtures/neon_fixtures.py
  test_runner/fixtures/pageserver/http.py
  test_runner/fixtures/utils.py
  test_runner/performance/test_gc_feedback.py
  test_runner/performance/test_hot_table.py
  test_runner/performance/test_layer_map.py
  test_runner/performance/test_parallel_copy_to.py
  test_runner/performance/test_random_writes.py
  test_runner/performance/test_seqscans.py
  test_runner/pg_clients/python/asyncpg/asyncpg_example.py
  test_runner/pg_clients/python/pg8000/pg8000_example.py
  test_runner/regress/test_auth.py
  test_runner/regress/test_backpressure.py
  test_runner/regress/test_broken_timeline.py
  test_runner/regress/test_build_info_metric.py
  test_runner/regress/test_gc_aggressive.py
  test_runner/regress/test_gc_cutoff.py
  test_runner/regress/test_import.py
  test_runner/regress/test_layer_writers_fail.py
  test_runner/regress/test_multixact.py
  test_runner/regress/test_old_request_lsn.py
  test_runner/regress/test_pageserver_restarts_under_workload.py
  test_runner/regress/test_parallel_copy.py
  test_runner/regress/test_proxy.py
  test_runner/regress/test_read_validation.py
  test_runner/regress/test_setup.py
  test_runner/regress/test_tenant_detach.py
  test_runner/regress/test_tenant_relocation.py
  test_runner/regress/test_tenants_with_remote_storage.py
  test_runner/regress/test_timeline_delete.py
  test_runner/regress/test_timeline_size.py
  test_runner/regress/test_truncate.py
  test_runner/regress/test_wal_acceptor.py
  test_runner/regress/test_wal_acceptor_async.py
Labels: run-benchmarks

#4796 Thin out TenantState metric, keep set of broken tenants
  pageserver/src/metrics.rs
  pageserver/src/tenant.rs
  pageserver/src/tenant/timeline.rs
  test_runner/fixtures/metrics.py
  test_runner/regress/test_tenant_detach.py
  test_runner/regress/test_tenants.py
Labels: /manual_release_instructions

#4654 support non-interactive transactions in sql-over-http
  Cargo.lock
  Cargo.toml
  proxy/src/http/sql_over_http.rs
Labels: approved-for-ci-run

#4795 make download function behavior more intuitive for prefix=None
  libs/remote_storage/src/s3_bucket.rs
  libs/remote_storage/tests/test_real_s3.rs
  test_runner/fixtures/neon_fixtures.py
Labels: a/tech_debt

#4844 pageserver: add unit test for deleted_at in IndexPart
  pageserver/src/tenant/remote_timeline_client/index.rs
Labels: c/storage/pageserver, a/tech_debt
