Repository neondatabase/neon, pull requests merged in 2023-06, with the labels that each got.

#4413 Compile PGX ULID extension
  Dockerfile.compute-node
Labels: /release-notes

#4412 Remove -ftree-vectorizer-verbose=0 option notrecognized by MaxOS/X c…
  pgxn/hnsw/Makefile
Labels: run-extra-build-macos

#4431 Fix `pgx_ulid` extension
  Dockerfile.compute-node
Labels: /release-notes

#4436 Add cold start test
  test_runner/performance/test_startup.py
Labels: c/test-runner, a/performance, a/benchmark, c/storage/compute

#4442 Compile rdkit
  Dockerfile.compute-node
Labels: /release-notes

#4558 Compile `pg_uuidv7`
  Dockerfile.compute-node
Labels: /release-notes

#4564 Compile `pg_roaringbitmap` extension
  Dockerfile.compute-node
Labels: /release-notes

#4585 Upload custom extensions to S3
  .github/workflows/build_and_test.yml
  Dockerfile.compute-node
Labels: run-benchmarks
