Repository neondatabase/neon, pull requests merged in 2025-06, with the labels that each got.

#11672 Add postgis to the test image
  compute/compute-node.Dockerfile
  docker-compose/compute_wrapper/Dockerfile
  docker-compose/docker-compose.yml
  docker-compose/docker_compose_test.sh
  docker-compose/ext-src/postgis-src/README-Neon.md
  docker-compose/ext-src/postgis-src/neon-test.sh
  docker-compose/ext-src/postgis-src/postgis-no-upgrade-test.patch
  docker-compose/ext-src/postgis-src/postgis-regular-v16.patch
  docker-compose/ext-src/postgis-src/postgis-regular-v17.patch
  docker-compose/ext-src/postgis-src/raster_outdb_template.sql
  docker-compose/ext-src/postgis-src/regular-test.sh
  docker-compose/run-tests.sh
Labels: team/perfcor

#12132 Remove the Flaky Test computed-columns from postgis v16
  docker-compose/ext-src/postgis-src/neon-test.sh
  docker-compose/ext-src/postgis-src/postgis-common-v16.patch
  docker-compose/ext-src/postgis-src/postgis-common-v17.patch
  docker-compose/ext-src/postgis-src/postgis-regular-v16.patch
  docker-compose/ext-src/postgis-src/postgis-regular-v17.patch
  docker-compose/ext-src/postgis-src/regular-test.sh
Labels: team/perfcor

#12169 Remove global static TENANTS
  pageserver/src/bin/pageserver.rs
  pageserver/src/tenant/mgr.rs
Labels: external

#12211 fix(pageserver): extend layer manager read guard threshold
  pageserver/src/tenant/timeline/layer_manager.rs
Labels: run-benchmarks

#12219 Improve logging for gc-compaction
  pageserver/src/tenant/timeline/compaction.rs
Labels: external

#12328 Update pgaudit to latest versions
  compute/compute-node.Dockerfile
Labels: /release-notes

#12364 Update rust to 1.88.0
  build-tools.Dockerfile
  pageserver/src/bin/test_helper_slow_client_reads.rs
  pageserver/src/tenant.rs
  rust-toolchain.toml
Labels: run-extra-build-macos

#12363 impr(ci): Refactor postgres Makefile targets to a separate makefile
  .dockerignore
  .github/workflows/build-macos.yml
  Dockerfile
  Makefile
  postgres.mk
Labels: run-extra-build-macos
